graph TD
    User[会員]
    Staff((在庫管理者))
    Master((システム管理者))

    subgraph System
        Use1(ログイン)
        Use2(商品検索)
        Use3(購入)
        Use4(在庫確認)
        Use5(売上集計)
        Use6(購入履歴)
        Use7(ログアウト)
    end

    User --> UC1
    User --> UC2
    User --> UC3
    User --> UC6
    User --> UC7

    Staff --> UC1
    Staff --> UC4
    Staff --> UC6
    Staff --> UC7

    Master --> UC1
    Master --> UC5
    Master --> UC7